"""Static provider type-to-module registration map."""

PROVIDER_MODULES = {
    "openai_chat_completions": "astrbot.core.provider.sources.openai_chat_completions_source",
    "openai_responses": "astrbot.core.provider.sources.openai_responses_source",
    "longcat_chat_completion": "astrbot.core.provider.sources.longcat_source",
    "minimax_token_plan": "astrbot.core.provider.sources.minimax_token_plan_source",
    "xiaomi_chat_completion": "astrbot.core.provider.sources.xiaomi_source",
    "xiaomi_token_plan": "astrbot.core.provider.sources.xiaomi_token_plan_source",
    "zhipu_chat_completion": "astrbot.core.provider.sources.zhipu_source",
    "groq_chat_completion": "astrbot.core.provider.sources.groq_source",
    "xai_chat_completion": "astrbot.core.provider.sources.xai_source",
    "aihubmix_chat_completion": "astrbot.core.provider.sources.oai_aihubmix_source",
    "openrouter_chat_completion": "astrbot.core.provider.sources.openrouter_source",
    "anthropic_chat_completion": "astrbot.core.provider.sources.anthropic_source",
    "kimi_code_chat_completion": "astrbot.core.provider.sources.kimi_code_source",
    "googlegenai_chat_completion": "astrbot.core.provider.sources.gemini_source",
    "sensevoice_stt_selfhost": "astrbot.core.provider.sources.sensevoice_selfhosted_source",
    "openai_whisper_api": "astrbot.core.provider.sources.whisper_api_source",
    "mimo_stt_api": "astrbot.core.provider.sources.mimo_stt_api_source",
    "openai_whisper_selfhost": "astrbot.core.provider.sources.whisper_selfhosted_source",
    "xinference_stt": "astrbot.core.provider.sources.xinference_stt_provider",
    "openai_tts_api": "astrbot.core.provider.sources.openai_tts_api_source",
    "mimo_tts_api": "astrbot.core.provider.sources.mimo_tts_api_source",
    "genie_tts": "astrbot.core.provider.sources.genie_tts",
    "edge_tts": "astrbot.core.provider.sources.edge_tts_source",
    "gsv_tts_selfhost": "astrbot.core.provider.sources.gsv_selfhosted_source",
    "gsvi_tts_api": "astrbot.core.provider.sources.gsvi_tts_source",
    "fishaudio_tts_api": "astrbot.core.provider.sources.fishaudio_tts_api_source",
    "dashscope_tts": "astrbot.core.provider.sources.dashscope_tts",
    "azure_tts": "astrbot.core.provider.sources.azure_tts_source",
    "minimax_tts_api": "astrbot.core.provider.sources.minimax_tts_api_source",
    "volcengine_tts": "astrbot.core.provider.sources.volcengine_tts",
    "gemini_tts": "astrbot.core.provider.sources.gemini_tts_source",
    "elevenlabs_tts_api": "astrbot.core.provider.sources.elevenlabs_tts_source",
    "openai_embedding": "astrbot.core.provider.sources.openai_embedding_source",
    "gemini_embedding": "astrbot.core.provider.sources.gemini_embedding_source",
    "nvidia_embedding": "astrbot.core.provider.sources.nvidia_embedding_source",
    "ollama_embedding": "astrbot.core.provider.sources.ollama_embedding_source",
    "vllm_rerank": "astrbot.core.provider.sources.vllm_rerank_source",
    "xinference_rerank": "astrbot.core.provider.sources.xinference_rerank_source",
    "bailian_rerank": "astrbot.core.provider.sources.bailian_rerank_source",
    "nvidia_rerank": "astrbot.core.provider.sources.nvidia_rerank_source",
}
